// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnE441kdbxwHOFKclbwogVYQGegF8mno',
    appId: '1:767531690117:web:a9f1f04869a7b8a91e61ec',
    messagingSenderId: '767531690117',
    projectId: 'medicalapp-93984',
    authDomain: 'medicalapp-93984.firebaseapp.com',
    storageBucket: 'medicalapp-93984.appspot.com',
    measurementId: 'G-KS53Z6XY45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbGXdoSPESEvnlyJVFfa_B2WCkHHBI4eU',
    appId: '1:767531690117:android:4817adcb51cf93591e61ec',
    messagingSenderId: '767531690117',
    projectId: 'medicalapp-93984',
    storageBucket: 'medicalapp-93984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwiK7mi2TTnkU5GFfpOm5cqdqp42yTmf4',
    appId: '1:767531690117:ios:c579ddfd4ebd062d1e61ec',
    messagingSenderId: '767531690117',
    projectId: 'medicalapp-93984',
    storageBucket: 'medicalapp-93984.appspot.com',
    iosBundleId: 'com.example.medicalapp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwiK7mi2TTnkU5GFfpOm5cqdqp42yTmf4',
    appId: '1:767531690117:ios:c579ddfd4ebd062d1e61ec',
    messagingSenderId: '767531690117',
    projectId: 'medicalapp-93984',
    storageBucket: 'medicalapp-93984.appspot.com',
    iosBundleId: 'com.example.medicalapp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVnE441kdbxwHOFKclbwogVYQGegF8mno',
    appId: '1:767531690117:web:903b5e3a7b1771581e61ec',
    messagingSenderId: '767531690117',
    projectId: 'medicalapp-93984',
    authDomain: 'medicalapp-93984.firebaseapp.com',
    storageBucket: 'medicalapp-93984.appspot.com',
    measurementId: 'G-BXS62RCRY5',
  );
}
